@PersoneApi_HostAddress = http://localhost:5290

GET {{PersoneApi_HostAddress}}/api/people
Accept: application/json

###

POST {{PersoneApi_HostAddress}}/api/people
Content-Type: application/json

{
  "name": "Mario",
  "surname": "Rossi",
  "email": "mario.rossi@example.com",
  "dateOfBirth": "1990-05-20T00:00:00"
}

###
